/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Cantact;

import DAO.UserDAO;
import Entity.User;
import Utile.MailMessage;
import Utile.MailSender;
import java.io.UnsupportedEncodingException;
import javax.mail.MessagingException;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;

/**
 *
 * @author gafsi
 */
public class PanelCantact extends javax.swing.JPanel {

    /**
     * Creates new form PanelForum
     */
    private static int userId;
    private final User user;
  

    public PanelCantact(int userid) {
        PanelCantact.userId = userid;
        user = new UserDAO().findUserById(userid);
        initComponents();
        googleMap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfMail = new javax.swing.JTextField();
        tfSubject = new javax.swing.JTextField();
        tfFile = new javax.swing.JTextField();
        btnFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMessage = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();
        tfNom = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 5));
        jPanel1.setLayout(null);
        add(jPanel1);
        jPanel1.setBounds(10, 40, 550, 460);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 5));

        tfMail.setText("E-mail");
        tfMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMailActionPerformed(evt);
            }
        });

        tfSubject.setText("Subject");

        tfFile.setText("File");

        btnFile.setText("jButton1");

        taMessage.setColumns(20);
        taMessage.setRows(5);
        jScrollPane1.setViewportView(taMessage);

        jButton2.setText("Envoyer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Resest");

        tfPassword.setText("Mot de passe");

        tfNom.setText("Nom");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfMail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNom))
                    .addComponent(tfPassword)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(tfSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tfFile, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMail, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(tfNom))
                .addGap(18, 18, 18)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfFile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel2);
        jPanel2.setBounds(590, 40, 690, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         envoyer_Email();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFile;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taMessage;
    private javax.swing.JTextField tfFile;
    private javax.swing.JTextField tfMail;
    private javax.swing.JTextField tfNom;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfSubject;
    // End of variables declaration//GEN-END:variables
private void envoyer_Email()
	{

	      try {
	    	  	if(tfMail!=null&&!tfMail.getText().toString().equals("")){
	    	  		    
	    	  			//envoyeur de message	

	    	  			/** SMPT de Gmail qui est gratuit avec numero de port= 456
	    	  		     *  nom utilisateur,mot de passe d'un compte gmail */
	    	  		    
	    	  			MailSender mail =new MailSender("smtp.gmail.com",465
					    		,tfMail.getText(),tfPassword.getText(),true);
					    //Message lui meme
	    	  			MailMessage msg =new MailMessage();
				       	//Source de message
					    msg.setFrom(new InternetAddress(tfMail.getText(),tfNom.getText()));
						//Destination 
                                            
					    msg.setTo("maher.gafsi@esprit.tn");
				        //Sujet de message
					    msg.setSubject(tfSubject.getText());
					    //Contenu de message
					    msg.setContent(taMessage.getText(),true);
					    //Piece jointe s'il y a lieu
				        if (!tfFile.getText().equals("")){
				        
				        	msg.setAttachmentURL(getstring(tfFile.getText()));
				        }
				        //Envoyer le message
				        mail.sendMessage(msg);
					
				}else {
					
					System.out.println("un des champ est vide ");
					
				}
			} catch (AddressException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
                                
				
			} catch (MessagingException e5) {
				// TODO Auto-generated catch block
				e5.printStackTrace();
				
			}catch (UnsupportedEncodingException e3) {
				// TODO Auto-generated catch block
				e3.printStackTrace();
				
			}
	

	}
private String getstring(String str){
		String fr = "" ;
		for(int i=0;str.length()>i;i++){
			if(str.substring(i,i+1).equals("\\")){
				fr=fr+"\\";
			}
			fr=fr+str.substring(i,i+1);
		}
		return fr;
	}
private void googleMap(){
   
    Browser browser;
   
    browser = new Browser();
     browser.executeJavaScript("var myLatlng = new google.maps.LatLng(37.0957036.,9.9689388);\n" +
                        "var marker = new google.maps.Marker({\n" +
                        "    position: myLatlng,\n" +
                        "    map: map,\n" +
                        "    title: 'Hello World!'\n" +
                        "});");
    BrowserView view = new BrowserView(browser);
    jPanel1.add(view);
    view.setBounds(0, 0, 550, 450);
     browser.loadURL("D:\\mes projets\\Java\\javaAllForDeal\\AllForDeal\\images\\map.html");
}
}
