/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DAO.CommandeDAO;
import DAO.LigneCommandeDAO;
import DAO.PanierDAO;
import DAO.ProduitDAO;
import Entity.Commande;
import Entity.LigneCommande;
import Entity.Panier;
import Entity.Produit;
import static GUI.FactureDispllay.DEST;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.GrayColor;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.DottedLineSeparator;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gafsi
 */
public class CommandeAdd extends javax.swing.JFrame {

    /**
     * Creates new form CommandeAdd
     */
        public static final String DEST = "C:/Facture/Facure.pdf";
    private float total=0;
    private List<LigneCommande>llc=new ArrayList<>();
    public CommandeAdd() {
        initComponents();
        loadProduits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnValider = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        lTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Liste des Produits :");

        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        lTotal.setText("lbTotal");

        jScrollPane2.setViewportView(txtPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lTotal))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnnuler)
                        .addGap(18, 18, 18)
                        .addComponent(btnValider))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnValider)
                            .addComponent(btnAnnuler))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lTotal)
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // TODO add your handling code here
        dispose();
        PanierDisplay p=new PanierDisplay();
        p.setVisible(true);
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
        
        Produit produit=new Produit();
        ProduitDAO prdouitDAO=new ProduitDAO();
        CommandeDAO commandeDAO=new CommandeDAO();
        Commande commande=new Commande();
        commande.setPanier(new PanierDAO().findPanierById(1));
        commande.setTotalcommande(total);
        commande.setValider(true);       
        commandeDAO.addCommande(commande);
        for(LigneCommande p : llc){
        if(p.getProduit().getQantite()-p.getQte()>=0){
        p.getProduit().setQantite(p.getProduit().getQantite()-p.getQte());
        prdouitDAO.modifier(p.getProduit());
        }
        File file = new File(DEST);
        file.getParentFile().mkdirs();
            try {
                createPdf(DEST);
            } catch (IOException ex) {
                Logger.getLogger(CommandeAdd.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
                Logger.getLogger(CommandeAdd.class.getName()).log(Level.SEVERE, null, ex);
            }       
        }
        JOptionPane.showMessageDialog(this, "la facture est générer dans le repertoire ");
           
    }//GEN-LAST:event_btnValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommandeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommandeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommandeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommandeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommandeAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lTotal;
    private javax.swing.JTextPane txtPane;
    // End of variables declaration//GEN-END:variables
private void loadProduits(){

        txtPane.setEditable(false);
        
        PanierDAO panierDAO=new PanierDAO();
        Panier panier=new Panier();
        panier=panierDAO.findPanierById(1);
        LigneCommandeDAO lcDAO=new LigneCommandeDAO();
        LigneCommande lc=new LigneCommande();
        llc=lcDAO.findLigneCommandByPanier( 1);
        for(LigneCommande produit : llc){
            txtPane.setText(txtPane.getText()+"\n"
            +produit.getProduit().getNom()+"    "+produit.getProduit().getPrix()
            +" DT \t\t"+produit.getQte()+" piéce \n");
            total+=produit.getProduit().getPrix()*produit.getQte();
        }
        lTotal.setText("Toatl : "+total+" DT");
}
public void createPdf(String filename) throws IOException, DocumentException {
    List<Commande> listecommandes = new ArrayList<>();    
    Produit produit=new Produit();
        ProduitDAO prdouitDAO=new ProduitDAO();
        CommandeDAO commandeDAO=new CommandeDAO();
        Commande commande=new Commande();
        listecommandes=commandeDAO.findCommandeByPanierId(1);
        
        Document document = new Document();
        Chunk linebreak = new Chunk(new DottedLineSeparator());
        float[] columnWidths = {5, 4, 3};
        PdfWriter.getInstance(document, new FileOutputStream(filename));
        document.open();
        PdfPTable table = new PdfPTable(columnWidths);
        table.setWidthPercentage(100);
        table.getDefaultCell().setUseAscender(true);
        table.getDefaultCell().setUseDescender(true);
        Font f = new Font(Font.FontFamily.HELVETICA, 13, Font.NORMAL, GrayColor.GRAYWHITE);
        PdfPCell cell = new PdfPCell(new Phrase("Facture", f));
        cell.setBackgroundColor(GrayColor.GRAYBLACK);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setColspan(3);
        table.addCell(cell);
        table.getDefaultCell().setBackgroundColor(new GrayColor(0.75f));
        for (int i = 0; i < 2; i++) {
            table.addCell("Produits");
            table.addCell("Quantité");
            table.addCell("Prix DT");
        }
        table.setHeaderRows(3);
        table.setFooterRows(1);
        table.getDefaultCell().setBackgroundColor(GrayColor.GRAYWHITE);
        table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
        for(LigneCommande p : llc){
           table.addCell(p.getProduit().getNom());
           table.addCell(""+p.getQte());
           table.addCell(""+p.getProduit().getPrix());
        }
      
        document.add(table);
        
    
        Paragraph paragraph1 = 
        new Paragraph("Prix Total : "+total+" DT");
        Paragraph paragraph2 = 
        new Paragraph("produit alka \t 100 DT \t 2");
        //Header header=new Header("header", "contenet");
//        paragraph1.setSpacingBefore(200f);
//        paragraph2.setSpacingBefore(5f);
        document.add(paragraph1);////     v vffff
        document.add(linebreak); 
        document.add(paragraph2);
        document.close();
    }
}
