/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Produits;

import DAO.CommentaireDAO;
import DAO.FavorisDAO;
import DAO.LigneCommandeDAO;
import DAO.ProduitDAO;
import DAO.UserDAO;
import Entity.Commentaire;
import Entity.Favoris;
import Entity.LigneCommande;
import Entity.Panier;
import Entity.Produit;
import Entity.User;
import GUI.FavorisDisplay;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author gafsi
 */
public class DialogueDetailProduit extends javax.swing.JDialog {

    /**
     * Creates new form DialogueAjouterService
     */
    private int posX = 0;   //Position X de la souris au clic
    private int posY = 0;   //Position Y de la souris au clic
    private static User user;
    private static Produit produit;
    private List<Integer> categoriesId = new ArrayList<Integer>();    
   // private List<Produit> listProduits = new ArrayList<>();
    private List<Commentaire> listCom;
    private Integer[] lid;
    private JTextField[] tabCom;
    private JLabel[] lmodifier;
    private JLabel[] lSupprimer;
    private static JLabel lPanierCount;

    public DialogueDetailProduit(java.awt.Frame parent, boolean modal, int userId, int produitId,JLabel lPanierCount) {
        super(parent, modal);
        initComponents();
        this.lPanierCount=lPanierCount;
        user = new UserDAO().findUserById(userId);
        produit = new ProduitDAO().findProduitById(produitId);
        setBounds(10, 10, 979, 546);
        tfNom.setText(produit.getNom());
        taDescription.setText(produit.getDescription());
        tfPrix.setText("" + produit.getPrix());
        tfPromotion.setText("" + produit.getPromotion());
        tfMarque.setText(produit.getMarque());
        if (produit.getImage() != null) {
            String imagePath = "src\\com\\images\\" + produit.getNom() + ".png";
            ImageIcon icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                    getScaledInstance(269, 338, Image.SCALE_DEFAULT));
            lImage.setIcon(icon1);
        }
        loadComments();
        commentsActions();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfMarque = new javax.swing.JTextField();
        tfPrix = new javax.swing.JTextField();
        tfNom = new javax.swing.JTextField();
        tfPromotion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        lImage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelComments = new javax.swing.JPanel();
        tfCommenter = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(211, 222, 234));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Détail Produit");

        btnExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dridi\\Desktop\\PI\\syrine\\AllForDeal\\images\\close.png")); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 800, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(211, 222, 234), 5, true));

        tfMarque.setEditable(false);
        tfMarque.setBackground(new java.awt.Color(255, 255, 255));
        tfMarque.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        tfMarque.setForeground(new java.awt.Color(102, 102, 102));
        tfMarque.setBorder(null);
        tfMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMarqueActionPerformed(evt);
            }
        });

        tfPrix.setEditable(false);
        tfPrix.setBackground(new java.awt.Color(255, 255, 255));
        tfPrix.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        tfPrix.setForeground(new java.awt.Color(102, 102, 102));
        tfPrix.setBorder(null);

        tfNom.setEditable(false);
        tfNom.setBackground(new java.awt.Color(255, 255, 255));
        tfNom.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        tfNom.setForeground(new java.awt.Color(102, 102, 102));
        tfNom.setText("Produit");
        tfNom.setBorder(null);

        tfPromotion.setEditable(false);
        tfPromotion.setBackground(new java.awt.Color(255, 255, 255));
        tfPromotion.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        tfPromotion.setForeground(new java.awt.Color(102, 102, 102));
        tfPromotion.setBorder(null);
        tfPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPromotionActionPerformed(evt);
            }
        });

        taDescription.setEditable(false);
        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        taDescription.setForeground(new java.awt.Color(102, 102, 102));
        taDescription.setRows(5);
        jScrollPane1.setViewportView(taDescription);

        panelComments.setPreferredSize(new java.awt.Dimension(280, 500));
        panelComments.setLayout(null);
        jScrollPane2.setViewportView(panelComments);

        jButton1.setText("Commenter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ajouter au Panier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ajouter au Favoris");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom :");

        jLabel3.setText("Prix :");

        jLabel4.setText("Promotion :");

        jLabel5.setText("Marque :");

        jLabel6.setText("Description");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lImage, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tfCommenter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lImage, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCommenter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 30, 980, 517);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMarqueActionPerformed

    private void tfPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPromotionActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        posX = evt.getX();    //Position X de la souris au clic
        posY = evt.getY();    //Position Y de la souris au clic
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int depX = evt.getX() - posX;
        int depY = evt.getY() - posY;
        setLocation(getX() + depX, getY() + depY);
    }//GEN-LAST:event_formMouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Commentaire com = new Commentaire();
        com.setCorps(tfCommenter.getText());
        com.setProduit(produit);
        com.setUser(user);
        CommentaireDAO comDao = new CommentaireDAO();
        comDao.addCommentaire(com);
        tfCommenter.setText("");
        panelComments.removeAll();
        panelComments.repaint();
        panelComments.revalidate();
        loadComments();
        commentsActions();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!new LigneCommandeDAO().exist( produit.getId(),user.getPanier().getId())){
        Panier panier=user.getPanier();
        LigneCommande lc=new LigneCommande();
        LigneCommandeDAO lcDao=new LigneCommandeDAO();
        lc.setProduit(produit);
        lc.setPanier(panier);
        lc.setQte(1);
        lcDao.addLigneCommande(lc);
        lPanierCount.setText(""+(Integer.parseInt(lPanierCount.getText())+1));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setIcon(new ImageIcon("images\\closeEntred.png"));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
         btnExit.setIcon(new ImageIcon("images\\close.png"));
    }//GEN-LAST:event_btnExitMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!new FavorisDAO().exist(user.getFavoris(), produit))         
       new FavorisDAO().addFavorisProduits(user.getFavoris(), produit);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogueDetailProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogueDetailProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogueDetailProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogueDetailProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogueDetailProduit dialog = new DialogueDetailProduit(new javax.swing.JFrame(), true, user.getId(), produit.getId()
                ,lPanierCount);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setBounds(10, 10, 838, 546);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lImage;
    private javax.swing.JPanel panelComments;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextField tfCommenter;
    private javax.swing.JTextField tfMarque;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrix;
    private javax.swing.JTextField tfPromotion;
    // End of variables declaration//GEN-END:variables
private void loadComments() {
        Commentaire com = new Commentaire();
        CommentaireDAO comDAO = new CommentaireDAO();
        listCom = comDAO.findCommentaireByProduit(produit.getId());
        lid = new Integer[listCom.size()];
        lmodifier = new JLabel[listCom.size()];
        lSupprimer = new JLabel[listCom.size()];
        tabCom = new JTextField[listCom.size()];
        JLabel[] lUser = new JLabel[listCom.size()];
        JLabel[] lDate = new JLabel[listCom.size()];
        int x = 10;
        int y = 26;
        for (int i = 0; i < listCom.size(); i++) {
            // ajout du proprietaire
            lUser[i] = new JLabel(listCom.get(i).getUser().getUsername());
            lUser[i].setBounds(x+5, y-18, 82, 17);
            lUser[i].setForeground(new Color(102,102,102));
            lUser[i].setFont(new java.awt.Font("Tahoma", 0, 11));
            panelComments.add(lUser[i]);
            // ajout de la date
            lDate[i] = new JLabel(""+listCom.get(i).getDateComm());
            lDate[i].setBounds(x+210, y-18, 82, 17);
            lDate[i].setForeground(new Color(102,102,102));
            lDate[i].setFont(new java.awt.Font("Tahoma", 0, 11));
            panelComments.add(lDate[i]);
            //ajout du corps
            tabCom[i] = new JTextField();
            tabCom[i].setText(listCom.get(i).getCorps());
            tabCom[i].setBounds(x, y, 270, 25);
            tabCom[i].setForeground(Color.black);
            tabCom[i].setFont(new java.awt.Font("Arial", 0, 12));
            tabCom[i].setEditable(false);
            panelComments.add(tabCom[i]);

            if (user.getId() == listCom.get(i).getUser().getId()) {
                //ajouts du boutton modifier 
                lmodifier[i] = new JLabel("Modifier");
                lmodifier[i].setBounds(x + 155, y + 25, 46, 13);
                lmodifier[i].setForeground(new java.awt.Color(51, 51, 255));
                lmodifier[i].setFont(new java.awt.Font("Tahoma", 1, 10));
                panelComments.add(lmodifier[i]);
                //ajouts du boutton supprimer
                lSupprimer[i] = new JLabel("Supprimer");
                lSupprimer[i].setBounds(x + 210, y + 25, 60, 13);
                lSupprimer[i].setForeground(new java.awt.Color(51, 51, 255));
                lSupprimer[i].setFont(new java.awt.Font("Tahoma", 1, 10));
                panelComments.add(lSupprimer[i]);
            }
            lid[i] = listCom.get(i).getId();
            y += 60;
        }
    }

    private void commentsActions() {
        for (int i = 0; i < listCom.size(); i++) {
            int j = i;
            if (lmodifier[i] != null) {
                lmodifier[i].addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        modifierMouseClicked(evt, j);
                    }

                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        modifierMouseEntered(evt, j);
                    }

                    @Override
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        modifierMouseExited(evt, j);
                    }
                });
                tabCom[i].addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyPressed(KeyEvent e) {
                        modifierKeyPressed(e, j);
                    }
                });

                lSupprimer[i].addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        supprimerMouseClicked(evt, j);
                    }

                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        supprimerMouseEntered(evt, j);
                    }

                    @Override
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        supprimerMouseExited(evt, j);
                    }

                });
            }

        }
    }

    private void modifierMouseClicked(MouseEvent evt, int j) {
        tabCom[j].setEditable(true);
//        removeAll();
//        repaint();
//        revalidate();
//        PanelSujetDisplay p = new PanelSujetDisplay(lid[i], userId);
//        p.setBounds(0, 0, 1310, 500);
//        add(p);
//        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }

    private void modifierMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void modifierMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void supprimerMouseClicked(MouseEvent evt, int i) {
        new CommentaireDAO().removeCommentaireById(listCom.get(i).getId());
        panelComments.removeAll();
        panelComments.repaint();
        panelComments.revalidate();
        loadComments();
        commentsActions();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }

    private void supprimerMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void supprimerMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void modifierKeyPressed(KeyEvent e, int j) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            Commentaire com = new Commentaire();
            CommentaireDAO comDAO = new CommentaireDAO();
            com.setProduit(produit);
            com.setCorps(tabCom[j].getText());
            com.setUser(user);
            com.setId(listCom.get(j).getId());
            comDAO.updateCommentaire(com);
            tabCom[j].setEditable(false);
        }
    }

}
