/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Produits;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author gafsi
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
     List<JLabel> l = new ArrayList<>();
      List<Integer> a = new ArrayList();
      int page = 1;
    public NewJFrame() {
        initComponents();
        test();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        l2.setText("jLabel1");
        l2.setOpaque(true);
        jPanel3.add(l2);
        l2.setBounds(180, 10, 150, 151);

        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("produit");
        l4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l4.setOpaque(true);
        jPanel3.add(l4);
        l4.setBounds(530, 10, 150, 151);

        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("produit");
        l1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l1.setOpaque(true);
        jPanel3.add(l1);
        l1.setBounds(10, 10, 150, 151);

        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("produit");
        l3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l3.setOpaque(true);
        jPanel3.add(l3);
        l3.setBounds(350, 10, 150, 151);

        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setText("produit");
        l8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l8.setOpaque(true);
        jPanel3.add(l8);
        l8.setBounds(530, 220, 150, 151);

        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("produit");
        l5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l5.setOpaque(true);
        jPanel3.add(l5);
        l5.setBounds(10, 220, 150, 151);

        l6.setText("jLabel1");
        l6.setOpaque(true);
        jPanel3.add(l6);
        l6.setBounds(180, 220, 150, 151);

        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l7.setText("produit");
        l7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l7.setOpaque(true);
        jPanel3.add(l7);
        l7.setBounds(350, 220, 150, 151);

        jButton1.setText("jButton1");
        jPanel3.add(jButton1);
        jButton1.setBounds(110, 160, 50, 40);

        jLabel9.setText("Produit");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 160, 100, 40);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 127, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon1 = new ImageIcon(new ImageIcon("C:\\Users\\gafsi\\Desktop\\integration java\\safa\\AllForDealSafa\\src\\com\\images\\mmm.png").getImage().
                getScaledInstance(150, 150, Image.SCALE_DEFAULT));
   if(a.size()>2*8){
       for (int i = 0; i < 8; i++) {
                l.get(i).setIcon(icon1);
            }
   }else{
        for (int i = 0; i < a.size()-8; i++) {
                l.get(i).setIcon(icon1);
            }
   }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         ImageIcon icon1 = new ImageIcon(new ImageIcon("C:\\Users\\gafsi\\Desktop\\integration java\\safa\\AllForDealSafa\\src\\com\\images\\lo.png").getImage().
                getScaledInstance(150, 150, Image.SCALE_DEFAULT));
   if(a.size()>8){
       for (int i = 0; i < 8; i++) {
                l.get(i).setIcon(icon1);
            }
   }else{
        for (int i = 0; i < a.size(); i++) {
                l.get(i).setIcon(icon1);
            }
   }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    // End of variables declaration//GEN-END:variables
private void test() {
       

        l.add(l1);
        l.add(l2);
        l.add(l3);
        l.add(l4);
        l.add(l5);
        l.add(l6);
        l.add(l7);
        l.add(l8);

        ImageIcon icon1 = new ImageIcon(new ImageIcon("C:\\Users\\gafsi\\Desktop\\integration java\\safa\\AllForDealSafa\\src\\com\\images\\lo.png").getImage().
                getScaledInstance(150, 150, Image.SCALE_DEFAULT));
        for (int i = 0; i < 13; i++) {
            a.add(i);
        }
        page = a.size() / 8;
        if (a.size() % 8 != 0) {
            page++;
        }
        if (a.size() <= 8) {
            for (int i = 0; i < a.size(); i++) {
                l.get(i).setIcon(icon1);
            }
        } else {
            for (int i = 0; i < page; i++) {
                jButton2.setText("" +( i + 1));
                jButton3.setText("" + i + 2);
            }
        }
        System.out.println("" + page);

        l1.setIcon(icon1);
        l2.setIcon(icon1);
        l3.setIcon(icon1);
        l4.setIcon(icon1);
        l5.setIcon(icon1);
        l6.setIcon(icon1);
        l8.setIcon(icon1);
        l8.setIcon(icon1);
    }
}
