/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Produits;

import Adapter.ProductsListAdapter;
import DAO.ProduitDAO;
import Entity.Produit;
import Entity.User;
import com.alee.extended.panel.GroupPanel;
import com.alee.extended.time.ClockType;
import com.alee.extended.time.WebClock;
import com.alee.managers.notification.NotificationIcon;
import com.alee.managers.notification.NotificationManager;
import com.alee.managers.notification.WebNotification;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author gafsi
 */
public class PanelProduitsProfile extends javax.swing.JPanel {

    /**
     * Creates new form PanelProduitsProfile
     */
    private List<Produit> produits=new ArrayList<Produit>();
    private int userId;
    public PanelProduitsProfile(int  userId) {
        initComponents();
        this.userId=userId;
        produits=new ProduitDAO().findProduitsByUser(userId);
        loadProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listProduits = new javax.swing.JList();
        labelCategorie = new javax.swing.JLabel();
        labelPrix = new javax.swing.JLabel();
        labelQuantite = new javax.swing.JLabel();
        labelPromotion = new javax.swing.JLabel();
        labelMarque = new javax.swing.JLabel();
        labelVente = new javax.swing.JLabel();
        labelPointBase = new javax.swing.JLabel();
        labelDateAjout = new javax.swing.JLabel();
        labelValider = new javax.swing.JLabel();
        tfCategorie = new javax.swing.JTextField();
        tfPrix = new javax.swing.JTextField();
        tfQuantité = new javax.swing.JTextField();
        tfPromotion = new javax.swing.JTextField();
        tfMarque = new javax.swing.JTextField();
        tfVente = new javax.swing.JTextField();
        tfPointDeBase = new javax.swing.JTextField();
        tfDateAjout = new javax.swing.JTextField();
        tfValider = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        listProduits.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listProduitsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listProduits);

        labelCategorie.setText("Catégorie");

        labelPrix.setText("Prix");

        labelQuantite.setText("Quantité");

        labelPromotion.setText("Promotion");

        labelMarque.setText("Marque");

        labelVente.setText("Vente");

        labelPointBase.setText("Points de base");

        labelDateAjout.setText("Date d'ajout");

        labelValider.setText("Valider");

        tfCategorie.setEditable(false);
        tfCategorie.setBackground(new java.awt.Color(255, 255, 255));
        tfCategorie.setBorder(null);

        tfPrix.setEditable(false);
        tfPrix.setBackground(new java.awt.Color(255, 255, 255));
        tfPrix.setBorder(null);

        tfQuantité.setEditable(false);
        tfQuantité.setBackground(new java.awt.Color(255, 255, 255));
        tfQuantité.setBorder(null);

        tfPromotion.setEditable(false);
        tfPromotion.setBackground(new java.awt.Color(255, 255, 255));
        tfPromotion.setBorder(null);

        tfMarque.setEditable(false);
        tfMarque.setBackground(new java.awt.Color(255, 255, 255));
        tfMarque.setBorder(null);

        tfVente.setEditable(false);
        tfVente.setBackground(new java.awt.Color(255, 255, 255));
        tfVente.setBorder(null);

        tfPointDeBase.setEditable(false);
        tfPointDeBase.setBackground(new java.awt.Color(255, 255, 255));
        tfPointDeBase.setBorder(null);

        tfDateAjout.setEditable(false);
        tfDateAjout.setBackground(new java.awt.Color(255, 255, 255));
        tfDateAjout.setBorder(null);

        tfValider.setEditable(false);
        tfValider.setBackground(new java.awt.Color(255, 255, 255));
        tfValider.setBorder(null);

        taDescription.setEditable(false);
        taDescription.setColumns(20);
        taDescription.setRows(5);
        taDescription.setBorder(null);
        jScrollPane2.setViewportView(taDescription);

        btnAdd.setIcon(new javax.swing.ImageIcon("D:\\mes projets\\Java\\javaAllForDeal\\AllForDeal\\images\\icon-add.png")); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon("D:\\mes projets\\Java\\javaAllForDeal\\AllForDeal\\images\\icon-update.png")); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRemove.setIcon(new javax.swing.ImageIcon("D:\\mes projets\\Java\\javaAllForDeal\\AllForDeal\\images\\icon-delete.png")); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(lImage);
        lImage.setBounds(0, 0, 260, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPointBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPointDeBase, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelVente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfVente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelMarque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPromotion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelQuantite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfQuantité, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPrix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelCategorie)
                        .addGap(43, 43, 43)
                        .addComponent(tfCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValider)
                            .addComponent(labelDateAjout))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfValider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDateAjout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAdd)
                                .addComponent(btnUpdate))
                            .addComponent(btnRemove)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCategorie)
                                    .addComponent(tfCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelPrix)
                                    .addComponent(tfPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelQuantite)
                                    .addComponent(tfQuantité, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelPromotion)
                                    .addComponent(tfPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelMarque)
                                    .addComponent(tfMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelVente)
                                    .addComponent(tfVente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfPointDeBase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPointBase))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelDateAjout)
                                    .addComponent(tfDateAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfValider, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelValider))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listProduitsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProduitsValueChanged
        // TODO add your handling code here:
         System.out.println("" + listProduits.getSelectedIndex());
        if (produits.size() != 0 && listProduits.getSelectedIndex() != -1) {
            labelCategorie.setText("Catégorie");
            labelDateAjout.setText("Date d'Ajout");
            labelMarque.setText("Marque");
            labelPointBase.setText("Points de base");
            labelPrix.setText("Prix");
            labelPromotion.setText("Promotion");
            labelValider.setText("Valider");
            labelVente.setText("Vente");
            labelQuantite.setText("Quantité");

            tfCategorie.setText(produits.get(listProduits.getSelectedIndex()).getCategorie_id().getNom());
            tfDateAjout.setText(""+produits.get(listProduits.getSelectedIndex()).getDateajout());
            tfMarque.setText(produits.get(listProduits.getSelectedIndex()).getMarque());
            tfPointDeBase.setText("" + produits.get(listProduits.getSelectedIndex()).getNbPointBase());
            tfPrix.setText(""+produits.get(listProduits.getSelectedIndex()).getPrix());
            tfPromotion.setText(""+produits.get(listProduits.getSelectedIndex()).getPromotion());
            tfQuantité.setText(""+produits.get(listProduits.getSelectedIndex()).getQantite());
            tfValider.setText(""+produits.get(listProduits.getSelectedIndex()).getValider());
            tfVente.setText(""+produits.get(listProduits.getSelectedIndex()).getNbvente());
            taDescription.setText(""+produits.get(listProduits.getSelectedIndex()).getDescription());
            String imagePath = "src\\com\\images\\" + produits.get(listProduits.getSelectedIndex()).getNom()+ ".png";

            ImageIcon icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                getScaledInstance(264, 200, Image.SCALE_DEFAULT));
           // lImage.setIcon(new ImageIcon("src\\com\\images\\lo.png"));
            lImage.setIcon(icon1);
        } else {
            labelCategorie.setText("");
            labelDateAjout.setText("");
            labelMarque.setText("");
            labelQuantite.setText("");
            labelPointBase.setText("");
            labelPrix.setText("");
            labelPromotion.setText("");
            labelValider.setText("");
            labelVente.setText("");      
            tfCategorie.setText("");
            tfDateAjout.setText("");
            tfMarque.setText("");
            tfPointDeBase.setText("");
            tfPrix.setText("");
            tfPromotion.setText("");
            tfQuantité.setText("");
            tfValider.setText("");
            tfVente.setText("");
            tfQuantité.setText("");
            lImage.setIcon(null);
            taDescription.setText("");
//            final WebNotification notificationPopup = new WebNotification ();
//                notificationPopup.setIcon ( NotificationIcon.tip );
//                notificationPopup.setDisplayTime ( 4000 );
//
//                final WebClock clock = new WebClock ();
//                clock.setClockType ( ClockType.timer );
//                clock.setTimeLeft ( 5000 );
//                clock.setTimePattern (  "'Vous n\'avez aucun Produit' ss " );
//                notificationPopup.setContent ( new GroupPanel ( clock ) );
//                NotificationManager.showNotification ( notificationPopup );
//                clock.start ();
     
        }
    }//GEN-LAST:event_listProduitsValueChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        new DialogueAjouterProduit(null, true, userId).setVisible(true);
         produits=new ProduitDAO().findProduitsByUser(userId);
         listProduits.setModel(new ProductsListAdapter(produits));
         if(produits.size()!=0)
             listProduits.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (produits.size() != 0 && listProduits.getSelectedIndex() != -1) {
            new DialogueModifierProduit(null, true, 
            produits.get(listProduits.getSelectedIndex()).getId()).setVisible(true);
            produits=new ProduitDAO().findProduitsByUser(userId);
            listProduits.setModel(new ProductsListAdapter(produits));
            if(produits.size()!=0)
             listProduits.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
         if (produits.size() != 0 && listProduits.getSelectedIndex() != -1) {
             new ProduitDAO().deleteProduit(produits.get(listProduits.getSelectedIndex()).getId());
             produits=new ProduitDAO().findProduitsByUser(userId);
             listProduits.setModel(new ProductsListAdapter(produits));
              if(produits.size()>0)
             listProduits.setSelectedIndex(0);
         }
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lImage;
    private javax.swing.JLabel labelCategorie;
    private javax.swing.JLabel labelDateAjout;
    private javax.swing.JLabel labelMarque;
    private javax.swing.JLabel labelPointBase;
    private javax.swing.JLabel labelPrix;
    private javax.swing.JLabel labelPromotion;
    private javax.swing.JLabel labelQuantite;
    private javax.swing.JLabel labelValider;
    private javax.swing.JLabel labelVente;
    private javax.swing.JList listProduits;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextField tfCategorie;
    private javax.swing.JTextField tfDateAjout;
    private javax.swing.JTextField tfMarque;
    private javax.swing.JTextField tfPointDeBase;
    private javax.swing.JTextField tfPrix;
    private javax.swing.JTextField tfPromotion;
    private javax.swing.JTextField tfQuantité;
    private javax.swing.JTextField tfValider;
    private javax.swing.JTextField tfVente;
    // End of variables declaration//GEN-END:variables
private void loadProducts(){
    listProduits.setModel(new ProductsListAdapter(produits));
}
}
