/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Home;

/**
 *
 * @author gafsi
 */
public class DialogueOk extends javax.swing.JDialog {

    /**
     * Creates new form DialogueOk
     */
    private int posX = 0;   //Position X de la souris au clic
    private int posY = 0;   //Position Y de la souris au clic
    private static String text;
    public DialogueOk(java.awt.Frame parent, boolean modal,String text) {
        super(parent, modal);
        initComponents();
        if(parent!=null)
        setBounds(parent.getBounds().x,parent.getBounds().y+50,360,189);
        else setBounds(400,100,360,189);
        taMessage.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taMessage = new javax.swing.JTextArea();
        btnOk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        taMessage.setEditable(false);
        taMessage.setBackground(new java.awt.Color(252, 252, 252));
        taMessage.setColumns(20);
        taMessage.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        taMessage.setForeground(new java.awt.Color(85, 85, 85));
        taMessage.setLineWrap(true);
        taMessage.setRows(2);
        taMessage.setBorder(null);
        taMessage.setOpaque(false);
        getContentPane().add(taMessage);
        taMessage.setBounds(60, 60, 260, 60);

        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOk.setText("  OK");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(140, 140, 68, 36);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\mes projets\\Java\\javaAllForDeal\\AllForDeal\\images\\are-you-sure.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 189);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnOkMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        posX = evt.getX();    //Position X de la souris au clic
        posY = evt.getY();    //Position Y de la souris au clic
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int depX = evt.getX() - posX;
        int depY = evt.getY() - posY;
        setLocation(getX() + depX, getY() + depY);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogueOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogueOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogueOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogueOk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogueOk dialog = new DialogueOk(new javax.swing.JFrame(), true,text);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea taMessage;
    // End of variables declaration//GEN-END:variables
}
