/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Home;

import DAO.UserDAO;
import Entity.User;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author gafsi
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    private int posX = 0;   //Position X de la souris au clic
    private int posY = 0;   //Position Y de la souris au clic

    public Register() {
        initComponents();
        setBounds(220, 20, 517, 661);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JLabel();
        btnMinimise = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfPasswordRetype = new javax.swing.JPasswordField();
        tfPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        lErrorUserName = new javax.swing.JLabel();
        lError = new javax.swing.JLabel();
        lErrorEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        btnClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dridi\\Desktop\\PI\\syrine\\AllForDeal\\images\\close.png")); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(482, 0, 30, 30);

        btnMinimise.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dridi\\Desktop\\PI\\syrine\\AllForDeal\\images\\minimise.png")); // NOI18N
        btnMinimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimiseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimiseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimiseMouseExited(evt);
            }
        });
        getContentPane().add(btnMinimise);
        btnMinimise.setBounds(450, 0, 30, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Déja Inscris ?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 560, 160, 30);

        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Se Connecter");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(300, 590, 80, 30);

        tfUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        tfUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserNameKeyPressed(evt);
            }
        });
        getContentPane().add(tfUserName);
        tfUserName.setBounds(50, 140, 260, 50);

        tfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEmailKeyPressed(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(50, 225, 260, 50);

        tfPasswordRetype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPasswordRetypeKeyPressed(evt);
            }
        });
        getContentPane().add(tfPasswordRetype);
        tfPasswordRetype.setBounds(50, 400, 260, 50);

        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(tfPassword);
        tfPassword.setBounds(50, 312, 260, 50);

        btnRegister.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dridi\\Desktop\\PI\\syrine\\AllForDeal\\images\\boutonRegister.png")); // NOI18N
        btnRegister.setBorder(null);
        btnRegister.setOpaque(false);
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(50, 560, 215, 57);
        getContentPane().add(lErrorUserName);
        lErrorUserName.setBounds(330, 140, 180, 50);

        lError.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lError.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lError);
        lError.setBounds(50, 460, 260, 30);
        getContentPane().add(lErrorEmail);
        lErrorEmail.setBounds(330, 224, 170, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dridi\\Desktop\\PI\\syrine\\AllForDeal\\images\\register.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 517, 661);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setIcon(new javax.swing.ImageIcon("images\\closeLoginEntred.png")); // NOI18N

    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setIcon(new javax.swing.ImageIcon("images\\closeLogin.png")); // NOI18N

    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMinimiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimiseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimiseMouseClicked

    private void btnMinimiseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimiseMouseEntered
        // TODO add your handling code here:
        btnMinimise.setIcon(new javax.swing.ImageIcon("images\\minimiseLoginEntred.png")); // NOI18N

    }//GEN-LAST:event_btnMinimiseMouseEntered

    private void btnMinimiseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimiseMouseExited
        // TODO add your handling code here:
        btnMinimise.setIcon(new javax.swing.ImageIcon("images\\minimiseLogin.png")); // NOI18N

    }//GEN-LAST:event_btnMinimiseMouseExited

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        // TODO add your handling code here:
        register();
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered
        // TODO add your handling code here:
        btnRegister.setIcon(new javax.swing.ImageIcon("images\\boutonRegisterEntred.png")); // NOI18N
    }//GEN-LAST:event_btnRegisterMouseEntered

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        // TODO add your handling code here:
        btnRegister.setIcon(new javax.swing.ImageIcon("images\\boutonRegister.png")); // NOI18N
    }//GEN-LAST:event_btnRegisterMouseExited

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:    
        btnLogin.setForeground(Color.red);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setForeground(Color.white);

    }//GEN-LAST:event_btnLoginMouseExited

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int depX = evt.getX() - posX;
        int depY = evt.getY() - posY;
        setLocation(getX() + depX, getY() + depY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        posX = evt.getX();    //Position X de la souris au clic
        posY = evt.getY();    //Position Y de la souris au clic
    }//GEN-LAST:event_formMousePressed

    private void tfUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER )
        register();
        
    }//GEN-LAST:event_tfUserNameKeyPressed

    private void tfEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmailKeyPressed
        // TODO add your handling code her:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER )
            register();
    }//GEN-LAST:event_tfEmailKeyPressed

    private void tfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER )
            register();
    }//GEN-LAST:event_tfPasswordKeyPressed

    private void tfPasswordRetypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordRetypeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER )
            register();
    }//GEN-LAST:event_tfPasswordRetypeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnMinimise;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lError;
    private javax.swing.JLabel lErrorEmail;
    private javax.swing.JLabel lErrorUserName;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JPasswordField tfPasswordRetype;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
private void register() {
        User user = new User();
        User userCheckUsername = null;
        User userCheckEmail = null;
        UserDAO userdao = new UserDAO();
        user.setUsername(tfUserName.getText());
        user.setEmail(tfEmail.getText());
        user.setPassword(tfPassword.getText());
        if (!tfUserName.getText().isEmpty() && !tfEmail.getText().isEmpty() && !tfPassword.getText().equals("")
                && !tfPasswordRetype.equals("")) {
            if (tfPassword.getText().equals(tfPasswordRetype.getText())) {
                userCheckUsername = userdao.findUserByUserName(tfUserName.getText());
                userCheckEmail = userdao.getUserByEmail(tfEmail.getText());
                if (userCheckUsername.getUsername() == null && userCheckEmail == null) {
                    userdao.insert(user);
                    new DialogueOk(this, true, "Votre compte est maintenant activé vous pouvez"
                            + " se connecter a tous moment").setVisible(true);
                    new Login().setVisible(true);
                    dispose();
                } else if (userCheckUsername.getUsername() != null) {
                    lErrorUserName.setIcon(new ImageIcon("images\\error.png"));
                    lErrorUserName.setText("nom d'utilisateur existe");

                } else if (userCheckEmail != null) {
                    lErrorEmail.setIcon(new ImageIcon("images\\error.png"));
                    lErrorEmail.setText("Email existe");
                }
            } else {
                lError.setText("les deux mot de passes ne sont pas identiques");
            }
        } else {
            if (tfUserName.getText().equals("")) {
                lErrorUserName.setText("champ obligatoire");
            }
            if (tfEmail.getText().equals("")) {
                lErrorEmail.setText("champ obligatoire");
            }
            if (tfPassword.getText().equals("")) {
                lError.setText("tous les champs sont obligatoires");
            }

        }
    }
}
