/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Profile;

import DAO.UserDAO;
import GUI.Forum.PanelForumProfile;
import GUI.Produits.PanelProduitsProfile;
import GUI.Services.PanelServicesProfile;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JLabel;

/**
 *
 * @author gafsi
 */
public class PanelUserProfile extends javax.swing.JPanel {

    /**
     * Creates new form PanelUserProfile
     */
    private static int userId;
    public PanelUserProfile(int userId) {
        this.userId=userId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDetails = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JLabel();
        btnProducts = new javax.swing.JLabel();
        btnServices = new javax.swing.JLabel();
        btnSubjects = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnDetails.setBackground(new java.awt.Color(204, 204, 204));
        btnDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnDetails.setText("Informations");
        btnDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetailsMouseExited(evt);
            }
        });

        btnChangePassword.setBackground(new java.awt.Color(204, 204, 204));
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setText("Changer mon mot de passe");

        btnProducts.setBackground(new java.awt.Color(204, 204, 204));
        btnProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnProducts.setText("Mes Produits");
        btnProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductsMouseClicked(evt);
            }
        });

        btnServices.setBackground(new java.awt.Color(204, 204, 204));
        btnServices.setForeground(new java.awt.Color(255, 255, 255));
        btnServices.setText("Mes Services");
        btnServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServicesMouseClicked(evt);
            }
        });

        btnSubjects.setBackground(new java.awt.Color(204, 204, 204));
        btnSubjects.setForeground(new java.awt.Color(255, 255, 255));
        btnSubjects.setText("Mes Sujets");
        btnSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnServices, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(btnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 180, 520);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(null);
        add(panelContent);
        panelContent.setBounds(180, 0, 1050, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailsMouseEntered
       
        
    }//GEN-LAST:event_btnDetailsMouseEntered

    private void btnDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailsMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDetailsMouseExited

    private void btnSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseClicked
        panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        PanelForumProfile p=new PanelForumProfile(userId);
        p.setBounds(0,0,1010,520);
        panelContent.add(p);
        inisilizeGrfic();
        btnSubjects.setOpaque(true);
        btnSubjects.setBackground(Color.white);
        btnSubjects.setForeground(Color.black);
        
       // panelContent.revalidate();
    }//GEN-LAST:event_btnSubjectsMouseClicked

    private void btnSubjectsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSubjectsMouseEntered

    private void btnSubjectsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubjectsMouseExited

    private void btnServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicesMouseClicked
        // TODO add your handling code here:
         panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        PanelServicesProfile p=new PanelServicesProfile(userId);
        p.setBounds(0,0,1010,520);
        panelContent.add(p);
        inisilizeGrfic();
        btnServices.setOpaque(true);
        btnServices.setBackground(Color.white);
        btnServices.setForeground(Color.black);
    }//GEN-LAST:event_btnServicesMouseClicked

    private void btnProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        PanelProduitsProfile p=new PanelProduitsProfile(userId);
        p.setBounds(0,0,1010,520);
        panelContent.add(p);
        inisilizeGrfic();
        btnProducts.setOpaque(true);
        btnProducts.setBackground(Color.white);
        btnProducts.setForeground(Color.black);
    }//GEN-LAST:event_btnProductsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnChangePassword;
    private javax.swing.JLabel btnDetails;
    private javax.swing.JLabel btnProducts;
    private javax.swing.JLabel btnServices;
    private javax.swing.JLabel btnSubjects;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
private void inisilizeGrfic(){
    JLabel[] tabButtons={btnChangePassword,btnDetails,btnProducts,btnServices,btnSubjects};
    for(int i=0;i<tabButtons.length;i++){
        tabButtons[i].setOpaque(false);
        tabButtons[i].setForeground(Color.white);
    }
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}
}
