/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Favoris;

import DAO.FavorisDAO;
import DAO.LigneCommandeDAO;
import DAO.ProduitDAO;
import DAO.UserDAO;
import Entity.Favoris;
import Entity.LigneCommande;
import Entity.Produit;
import Entity.User;
import GUI.Produits.DialogueDetailProduit;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author gafsi
 */
public class PanelFavoris extends javax.swing.JPanel {

    /**
     * Creates new form PanelForum
     */
    private static int userId;
    private final User user;
    private Favoris favoris;
    private List<Produit> produits = new ArrayList<>();
    private final List<JLabel> lDelete = new ArrayList<>();
    private final List<JLabel> lNom = new ArrayList<>();
    private final List<JLabel> lImage = new ArrayList<>();
    private final List<JLabel> btnsPanier = new ArrayList<>();
    private final List<JLabel> lPromotion = new ArrayList<>();
    private final List<JLabel> lPrix = new ArrayList<>();
    private final List<JLabel> lDetails = new ArrayList<>();
    private final List<JSeparator> separateur = new ArrayList<>();
    private final JLabel lPanierCount;

    public PanelFavoris(int userid, JLabel lPanierCount) {
        PanelFavoris.userId = userid;
        this.lPanierCount = lPanierCount;
        user = new UserDAO().findUserById(userid);
        favoris = user.getFavoris();
        
        initComponents();
        loadProducts();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelProduit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jScrollPane1.setBorder(null);

        panelProduit.setBackground(new java.awt.Color(255, 255, 255));
        panelProduit.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Vos Favoris");
        panelProduit.add(jLabel4);
        jLabel4.setBounds(300, 0, 170, 40);

        jLabel1.setBackground(new java.awt.Color(255, 146, 100));
        jLabel1.setOpaque(true);
        panelProduit.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 39);

        jLabel2.setBackground(new java.awt.Color(188, 188, 188));
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("Image");
        panelProduit.add(jLabel2);
        jLabel2.setBounds(70, 50, 40, 14);

        jLabel3.setBackground(new java.awt.Color(188, 188, 188));
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setText("Nom du produit");
        panelProduit.add(jLabel3);
        jLabel3.setBounds(200, 50, 90, 14);

        jLabel5.setBackground(new java.awt.Color(188, 188, 188));
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setText("Prix unitaire");
        panelProduit.add(jLabel5);
        jLabel5.setBounds(330, 50, 70, 14);

        jLabel6.setBackground(new java.awt.Color(188, 188, 188));
        jLabel6.setForeground(new java.awt.Color(188, 188, 188));
        jLabel6.setText("Plus de détails");
        panelProduit.add(jLabel6);
        jLabel6.setBounds(650, 50, 100, 14);

        jLabel7.setBackground(new java.awt.Color(188, 188, 188));
        jLabel7.setForeground(new java.awt.Color(188, 188, 188));
        jLabel7.setText("Promotion");
        panelProduit.add(jLabel7);
        jLabel7.setBounds(430, 50, 70, 14);

        jLabel8.setBackground(new java.awt.Color(188, 188, 188));
        jLabel8.setForeground(new java.awt.Color(188, 188, 188));
        jLabel8.setText("Ajouter au panier");
        panelProduit.add(jLabel8);
        jLabel8.setBounds(510, 50, 100, 14);

        jScrollPane1.setViewportView(panelProduit);

        add(jScrollPane1);
        jScrollPane1.setBounds(270, 30, 770, 470);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelProduit;
    // End of variables declaration//GEN-END:variables
private void loadProducts() {
        //produits = user.getFavoris().getProduit();
        produits=new FavorisDAO().findProduitsByFavorisId(user.getFavoris().getId());
        if (produits.size() > 0) {
            panelProduit.setPreferredSize(new Dimension(100, produits.size() * 182));
            int x = 10;
            int y = 100;
            for (int i = 0; i < produits.size(); i++) {
                //ajout du bouton pour la supprission
                lDelete.add(new JLabel(new ImageIcon("images\\closeEntred.png")));
                panelProduit.add(lDelete.get(i));
                lDelete.get(i).setBounds(x, y + 20, 30, 20);
                //Ajout de l'image de produit
                Produit p = new ProduitDAO().findProduitById(produits.get(i).getId());
                String imagePath = "src\\com\\images\\" + p.getNom() + ".png";
                ImageIcon icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                        getScaledInstance(80, 70, Image.SCALE_DEFAULT));
                lImage.add(new JLabel(icon1));
                panelProduit.add(lImage.get(i));
                lImage.get(i).setBounds(x + 50, y, 80, 70);
                //Ajout du nom du produit
                lNom.add(new JLabel(p.getNom()));
                panelProduit.add(lNom.get(i));
                lNom.get(i).setBounds(x + 200, y + 20, 90, 30);
                //Ajout du prix unitaire
                lPrix.add(new JLabel(p.getPrix() + " DT"));
                panelProduit.add(lPrix.get(i));
                lPrix.get(i).setBounds(x + 330, y + 20, 60, 30);
                //Ajout de la promotion
                lPromotion.add(new JLabel(p.getPromotion() + " %"));
                panelProduit.add(lPromotion.get(i));
                lPromotion.get(i).setBounds(x + 430, y + 20, 50, 30);
                //Ajout du bouuton pour l'ajout au panier
                if (!new LigneCommandeDAO().exist(p.getId(), user.getPanier().getId())) {
                    imagePath = "images\\btnPanier.png";
                } else {
                    imagePath = "images\\btnPanierDisabled.png";
                }
                icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                        getScaledInstance(30, 30, Image.SCALE_DEFAULT));
                btnsPanier.add(new JLabel(icon1));
                panelProduit.add(btnsPanier.get(i));
                btnsPanier.get(i).setBounds(x + 540, y + 20, 30, 30);
                //Ajout du bouuton plus de détails
                imagePath = "images\\add.png";
                icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                        getScaledInstance(20, 20, Image.SCALE_DEFAULT));
                lDetails.add(new JLabel(icon1));
                panelProduit.add(lDetails.get(i));
                lDetails.get(i).setBounds(x + 690, y + 20, 30, 30);
                //Ajout du separateur
                separateur.add(new JSeparator());
                panelProduit.add(separateur.get(i));
                separateur.get(i).setBounds(0, y + 82, 740, 10);
                y += 100;
            }

        }
        Actions();
    }

    private void Actions() {
        for (int i = 0; i < produits.size(); i++) {
            int j = i;
            lDelete.get(j).addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    deleteMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    deleteMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    deleteMouseExited(evt, j);
                }

            });
            lDetails.get(i).addMouseListener(new java.awt.event.MouseAdapter() {
//                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    detailMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    detailMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    detailMouseExited(evt, j);
                }

            });
            btnsPanier.get(i).addMouseListener(new java.awt.event.MouseAdapter() {
//                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btnPanierMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnsPanierMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnsPanierMouseExited(evt, j);
                }

            });

        }
    }

    private void deleteMouseClicked(MouseEvent evt, int i) {

        new FavorisDAO().removeProduitById(produits.get(i).getId());
        produits.remove(i);
       // favoris = user.getFavoris();
        removeAll();
        repaint();
        revalidate();
        initComponents();
        loadProducts();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }

    private void deleteMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void deleteMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void detailMouseClicked(MouseEvent evt, int i) {
        new DialogueDetailProduit(null, true, user.getId(), produits.get(i).getId(), lPanierCount).setVisible(true);

    }

    private void detailMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void detailMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void btnsPanierMouseEntered(MouseEvent evt, int j) {
        if (!new LigneCommandeDAO().exist(produits.get(j).getId(), user.getPanier().getId()))
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        else setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void btnPanierMouseClicked(MouseEvent evt, int j) {
         if (!new LigneCommandeDAO().exist(produits.get(j).getId(), user.getPanier().getId())) {
        LigneCommande lc=new LigneCommande();
        LigneCommandeDAO lcDao=new LigneCommandeDAO();
        lc.setProduit(produits.get(j));
        lc.setPanier(user.getPanier());
        lc.setQte(1);
        lcDao.addLigneCommande(lc);
        lPanierCount.setText(""+(Integer.parseInt(lPanierCount.getText())+1));
       
       
         }
    }

    private void btnsPanierMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

}
