/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panier;

import DAO.LigneCommandeDAO;
import DAO.ProduitDAO;
import DAO.UserDAO;
import Entity.LigneCommande;
import Entity.Panier;
import Entity.Produit;
import Entity.User;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author gafsi
 */
public class PanelPanier extends javax.swing.JPanel {

    /**
     * Creates new form PanelForum
     */
    private static int userId;
    private final User user;
    private final Panier panier;
    private List<LigneCommande> ligneCommands = new ArrayList<>();
    private final List<JLabel> lDelete = new ArrayList<>();
    private final List<JLabel> lNom = new ArrayList<>();
    private final List<JLabel> lImage = new ArrayList<>();
    private final List<JLabel> lTotal = new ArrayList<>();
    private final List<JLabel> lPromotion = new ArrayList<>();
    private final List<JLabel> lPrix = new ArrayList<>();
    private final List<JSpinner> lQte = new ArrayList<>();
    private final List<JSeparator> separateur = new ArrayList<>();
    private final JLabel f;
    private float prixToatl=0;
    private float prixAP=0;

    public PanelPanier(int userid, JLabel f) {
        this.f = f;
        PanelPanier.userId = userid;
        user = new UserDAO().findUserById(userid);
        panier = user.getPanier();
        initComponents();
        loadProducts();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelProduit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lImageDetail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lPrixAP = new javax.swing.JLabel();
        lPrixTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jScrollPane1.setBorder(null);

        panelProduit.setBackground(new java.awt.Color(56, 59, 66));
        panelProduit.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dridi\\Desktop\\PI\\syrine\\AllForDeal\\images\\shopping-cart.jpg")); // NOI18N
        panelProduit.add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 39);

        jLabel2.setBackground(new java.awt.Color(188, 188, 188));
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("Image");
        panelProduit.add(jLabel2);
        jLabel2.setBounds(70, 50, 40, 14);

        jLabel3.setBackground(new java.awt.Color(188, 188, 188));
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setText("Nom du produit");
        panelProduit.add(jLabel3);
        jLabel3.setBounds(180, 50, 90, 14);

        jLabel4.setBackground(new java.awt.Color(188, 188, 188));
        jLabel4.setForeground(new java.awt.Color(188, 188, 188));
        jLabel4.setText("Quantité");
        panelProduit.add(jLabel4);
        jLabel4.setBounds(310, 50, 60, 14);

        jLabel5.setBackground(new java.awt.Color(188, 188, 188));
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setText("Prix unitaire");
        panelProduit.add(jLabel5);
        jLabel5.setBounds(410, 50, 70, 14);

        jLabel6.setBackground(new java.awt.Color(188, 188, 188));
        jLabel6.setForeground(new java.awt.Color(188, 188, 188));
        jLabel6.setText("Promotion");
        panelProduit.add(jLabel6);
        jLabel6.setBounds(510, 50, 70, 14);

        jLabel7.setBackground(new java.awt.Color(188, 188, 188));
        jLabel7.setForeground(new java.awt.Color(188, 188, 188));
        jLabel7.setText("Total");
        panelProduit.add(jLabel7);
        jLabel7.setBounds(600, 50, 40, 14);

        jScrollPane1.setViewportView(panelProduit);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 20, 671, 360);

        jButton1.setText("Continuer Vos achats");
        add(jButton1);
        jButton1.setBounds(40, 450, 150, 30);

        jButton2.setText("Valider mon panier");
        add(jButton2);
        jButton2.setBounds(560, 450, 150, 30);
        add(lImageDetail);
        lImageDetail.setBounds(830, 20, 270, 360);

        jLabel9.setText("Prix avant Promotion :");
        add(jLabel9);
        jLabel9.setBounds(520, 380, 120, 30);

        jLabel10.setText("Prix Total :");
        add(jLabel10);
        jLabel10.setBounds(520, 410, 110, 30);

        lPrixAP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lPrixAP.setText("lPrixAP");
        add(lPrixAP);
        lPrixAP.setBounds(640, 380, 70, 30);

        lPrixTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lPrixTotal.setText("jLabel11");
        add(lPrixTotal);
        lPrixTotal.setBounds(640, 410, 70, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lImageDetail;
    private javax.swing.JLabel lPrixAP;
    private javax.swing.JLabel lPrixTotal;
    private javax.swing.JPanel panelProduit;
    // End of variables declaration//GEN-END:variables
private void loadProducts() {
        ligneCommands = new LigneCommandeDAO().findLigneCommandByPanier(panier.getId());
        if (ligneCommands.size() > 0) {
            panelProduit.setPreferredSize(new Dimension(100, ligneCommands.size() * 182));
            int x = 10;
            int y = 100;
            for (int i = 0; i < ligneCommands.size(); i++) {
                //ajout du bouton pour la supprission
                lDelete.add(new JLabel(new ImageIcon("images\\closeEntred.png")));
                panelProduit.add(lDelete.get(i));
                lDelete.get(i).setBounds(x, y + 20, 30, 20);
                //Ajout de l'image de produit
                Produit p = new ProduitDAO().findProduitById(ligneCommands.get(i).getProduit().getId());
                String imagePath = "src\\com\\images\\" + p.getNom() + ".png";
                ImageIcon icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                        getScaledInstance(80, 70, Image.SCALE_DEFAULT));
                lImage.add(new JLabel(icon1));
                panelProduit.add(lImage.get(i));
                lImage.get(i).setBounds(x + 50, y, 80, 70);
                //Ajout du nom du produit
                lNom.add(new JLabel(p.getNom()));
                panelProduit.add(lNom.get(i));
                lNom.get(i).setBounds(x + 170, y + 20, 90, 30);
                //Ajout du Qte
                lQte.add(new JSpinner(new SpinnerNumberModel(ligneCommands.get(i).getQte(), 1, 10, 1)));
                panelProduit.add(lQte.get(i));
                lQte.get(i).setBounds(x + 300, y + 20, 50, 30);
                //Ajout du prix unitaire
                lPrix.add(new JLabel( p.getPrix()+" DT"));
                panelProduit.add(lPrix.get(i));
                lPrix.get(i).setBounds(x + 400, y + 20, 60, 30);
                //Ajout de la promotion
                lPromotion.add(new JLabel(p.getPromotion()+" %"));
                panelProduit.add(lPromotion.get(i));
                lPromotion.get(i).setBounds(x + 500, y + 20, 50, 30);
                //Ajout du prix unitaire
                float total = p.getPrix() * ligneCommands.get(i).getQte();
                if (p.getPromotion() != 0) {
                    total = (p.getPrix() - (p.getPrix() * p.getPromotion() / 100)) * ligneCommands.get(i).getQte();
                }
                lTotal.add(new JLabel(total+" DT"));
                panelProduit.add(lTotal.get(i));
                lTotal.get(i).setBounds(x + 600, y + 20, 60, 30);
                //Ajout du separateur
                separateur.add(new JSeparator());
                panelProduit.add(separateur.get(i));
                separateur.get(i).setBounds(0, y + 82, 670, 10);
                y += 100;
            }

        }
        Actions();
        calculerTotal();
    }

    private void Actions() {
        for (int i = 0; i < ligneCommands.size(); i++) {
            int j = i;
            lDelete.get(i).addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    deleteMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    deleteMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    deleteMouseExited(evt, j);
                }

            });
                    lImage.get(i).addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    imageMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    imageMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    imageMouseExited(evt, j);
                }

            });

        }
    }

    private void deleteMouseClicked(MouseEvent evt, int i) {
        new LigneCommandeDAO().removeLigneCommandeById(ligneCommands.get(i).getId());
        ligneCommands = new LigneCommandeDAO().findLigneCommandByPanier(panier.getId());
        f.setText("" + ligneCommands.size());
        removeAll();
        repaint();
        revalidate();
        initComponents();
        loadProducts();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        calculerTotal();

    }

    private void deleteMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void deleteMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    
    
    private void imageMouseClicked(MouseEvent evt, int i) {
       
        Produit p = new ProduitDAO().findProduitById(ligneCommands.get(i).getProduit().getId());
                String imagePath = "src\\com\\images\\" + p.getNom() + ".png";
                ImageIcon icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                        getScaledInstance(270, 360, Image.SCALE_DEFAULT));
                lImageDetail.setIcon(icon1);

    }

    private void imageMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void imageMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    
    private void calculerTotal(){
        prixAP=0;
        prixToatl=0;
        ligneCommands.stream().map((ligneCommand) -> {
            prixAP += (ligneCommand.getQte() * ligneCommand.getProduit().getPrix());
            return ligneCommand;
        }).forEach((ligneCommand) -> {
            if (ligneCommand.getProduit().getPromotion() != 0) {
                prixToatl += (ligneCommand.getProduit().getPrix() - (ligneCommand.getProduit().getPrix() * ligneCommand.getProduit().getPromotion() / 100)) * ligneCommand.getQte();
            } else {
                prixToatl += (ligneCommand.getQte() * ligneCommand.getProduit().getPrix());
            }
        });
        lPrixAP.setText(""+prixAP+" DT");
        lPrixTotal.setText(""+prixToatl+" DT");
    }
}
