/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import DAO.CategorieDAO;
import DAO.FavorisDAO;
import DAO.ProduitDAO;
import Entity.Categorie;
import Entity.Produit;
import Utile.coucheMetier;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author Dridi
 */
public class PanelCategorieProduit extends javax.swing.JPanel {

    private List<Categorie> cats = new ArrayList<>();
    private final List<JLabel> lDelete = new ArrayList<>();
    private final List<JLabel> lNom = new ArrayList<>();
    private final List<JLabel> lDescription = new ArrayList<>();
    private final List<JLabel> lDetails = new ArrayList<>();
    private final List<JLabel> lModif = new ArrayList<>();
    private final List<JSeparator> separateur = new ArrayList<>();

    /**
     * Creates new form PanelCategorieProduit
     */
    public PanelCategorieProduit() {
        initComponents();
        cats = new CategorieDAO().findAll();
        loadCategories();
        setBounds(0, 0, 1162, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();

        setLayout(null);

        jLabel2.setBackground(new java.awt.Color(188, 188, 188));
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("Nom");
        add(jLabel2);
        jLabel2.setBounds(60, 60, 40, 14);

        jLabel3.setBackground(new java.awt.Color(188, 188, 188));
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setText("Description");
        add(jLabel3);
        jLabel3.setBounds(200, 60, 90, 14);

        jLabel5.setBackground(new java.awt.Color(188, 188, 188));
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setText("Actions");
        add(jLabel5);
        jLabel5.setBounds(360, 60, 70, 14);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Liste des catégories produits");
        add(jLabel4);
        jLabel4.setBounds(300, 0, 520, 40);

        jLabel1.setBackground(new java.awt.Color(255, 146, 100));
        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1162, 39);

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        add(btnAjouter);
        btnAjouter.setBounds(520, 40, 69, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private void loadCategories() {
        //produits = user.getFavoris().getProduit();
        cats = new CategorieDAO().findAll();
        if (cats.size() > 0) {
            // setPreferredSize(new Dimension(100, produits.size() * 182));
            int x = 10;
            int y = 100;
            for (int i = 0; i < cats.size(); i++) {

                //Ajout du nom du categorie
                Produit p = new ProduitDAO().findProduitById(cats.get(i).getId());
                String imagePath = "src\\com\\images\\" + p.getNom() + ".png";
                ImageIcon icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                        getScaledInstance(80, 70, Image.SCALE_DEFAULT));
                lNom.add(new JLabel(p.getNom()));
                add(lNom.get(i));
                lNom.get(i).setBounds(x + 50, y, 80, 70);
                //Ajout de la description du categories
                lDescription.add(new JLabel(p.getDescription()));
                add(lDescription.get(i));
                lDescription.get(i).setBounds(x + 200, y + 20, 90, 30);
                //Ajout du bouuton plus de détails
//                imagePath = "images\\add.png";
//                icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
//                        getScaledInstance(20, 20, Image.SCALE_DEFAULT));
//                lDetails.add(new JLabel(icon1));
//                add(lDetails.get(i));
//                lDetails.get(i).setBounds(x + 330, y + 20, 60, 30);
                //ajout du bouton pour la supprission
                lDelete.add(new JLabel(new ImageIcon("images\\closeEntred.png")));
                add(lDelete.get(i));
                lDelete.get(i).setBounds(x + 330, y + 20, 30, 20);
                //ajout du bouton modifier
                imagePath = "images\\modif.png";
                icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                getScaledInstance(20, 20, Image.SCALE_DEFAULT));
                lModif.add(new JLabel(icon1));
                add(lModif.get(i));
                lModif.get(i).setBounds(x + 390, y + 20, 30, 20);
                //Ajout du separateur
                separateur.add(new JSeparator());
                add(separateur.get(i));
                separateur.get(i).setBounds(0, y + 82, 1162, 10);
                y += 100;
            }

        }
        Actions();
    }

    private void Actions() {
        for (int i = 0; i < cats.size(); i++) {
            int j = i;
            lDelete.get(j).addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    deleteMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    deleteMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    deleteMouseExited(evt, j);
                }

            });
//            lDetails.get(i).addMouseListener(new java.awt.event.MouseAdapter() {
////                @Override
//                public void mouseClicked(java.awt.event.MouseEvent evt) {
//                    detailMouseClicked(evt, j);
//                }
//
//                @Override
//                public void mouseEntered(java.awt.event.MouseEvent evt) {
//                    detailMouseEntered(evt, j);
//                }
//
//                @Override
//                public void mouseExited(java.awt.event.MouseEvent evt) {
//                    detailMouseExited(evt, j);
//                }
//
//            });

        }
    }

    private void deleteMouseClicked(MouseEvent evt, int i) {

        new CategorieDAO().removecategorieById(cats.get(i).getId());
        cats.remove(i);
        // favoris = user.getFavoris();
        removeAll();
        repaint();
        revalidate();
        initComponents();
        loadCategories();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }

    private void deleteMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void deleteMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
//
//    private void detailMouseClicked(MouseEvent evt, int i) {
//    }
//
//    private void detailMouseEntered(MouseEvent evt, int j) {
//        setCursor(new Cursor(Cursor.HAND_CURSOR));
//
//    }
//
//    private void detailMouseExited(MouseEvent evt, int j) {
//        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
//    }

}
