/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import DAO.FavorisDAO;
import DAO.ProduitDAO;
import DAO.PubliciteDAO;
import Entity.Produit;
import Entity.Publicite;
import GUI.Produits.DialogueDetailProduit;
import GUI.Profile.DialogueDetailPublicite;
import GUI.Publicite.PubliciteUpdate;
import GUI.Publicite.PublicteAdd;
import Utile.coucheMetier;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author Dridi
 */
public class PanelPubliciteAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelPublicite
     */
    private List<Publicite> pubs = new ArrayList<>();
    private final List<JLabel> lDelete = new ArrayList<>();
    private final List<JLabel> lImage = new ArrayList<>();
    private final List<JLabel> lType = new ArrayList<>();
    private final List<JLabel> lSujet = new ArrayList<>();
    private final List<JLabel> lDate = new ArrayList<>();
    private final List<JLabel> lLieu = new ArrayList<>();
    private final List<JLabel> lDetails = new ArrayList<>();
    private final List<JLabel> lModif = new ArrayList<>();
    private final List<JSeparator> separateur = new ArrayList<>();

    public PanelPubliciteAdmin() {
        initComponents();
        pubs = new PubliciteDAO().findAll();
        loadPubs();
        setBounds(0, 0, 1162, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();

        setLayout(null);

        jLabel2.setBackground(new java.awt.Color(188, 188, 188));
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("Image");
        add(jLabel2);
        jLabel2.setBounds(80, 60, 40, 14);

        jLabel3.setBackground(new java.awt.Color(188, 188, 188));
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setText("Type");
        add(jLabel3);
        jLabel3.setBounds(210, 60, 90, 14);

        jLabel5.setBackground(new java.awt.Color(188, 188, 188));
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setText("Sujet");
        add(jLabel5);
        jLabel5.setBounds(340, 60, 70, 14);

        jLabel7.setBackground(new java.awt.Color(188, 188, 188));
        jLabel7.setForeground(new java.awt.Color(188, 188, 188));
        jLabel7.setText("nom");
        add(jLabel7);
        jLabel7.setBounds(440, 60, 70, 14);

        jLabel8.setBackground(new java.awt.Color(188, 188, 188));
        jLabel8.setForeground(new java.awt.Color(188, 188, 188));
        jLabel8.setText("lieu");
        add(jLabel8);
        jLabel8.setBounds(550, 60, 30, 14);

        jLabel6.setBackground(new java.awt.Color(188, 188, 188));
        jLabel6.setForeground(new java.awt.Color(188, 188, 188));
        jLabel6.setText("Action");
        add(jLabel6);
        jLabel6.setBounds(770, 60, 100, 14);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Liste des publicités");
        add(jLabel4);
        jLabel4.setBounds(100, 0, 210, 40);

        jLabel1.setBackground(new java.awt.Color(255, 146, 100));
        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1162, 39);

        jLabel9.setBackground(new java.awt.Color(188, 188, 188));
        jLabel9.setForeground(new java.awt.Color(188, 188, 188));
        jLabel9.setText("date");
        add(jLabel9);
        jLabel9.setBounds(660, 60, 100, 14);

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        add(btnAjouter);
        btnAjouter.setBounds(800, 40, 69, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
          new PublicteAdd().setVisible(true);
    }//GEN-LAST:event_btnAjouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void loadPubs() {
        pubs = new PubliciteDAO().findAll();
        if (pubs.size() > 0) {
            // setPreferredSize(new Dimension(100, produits.size() * 182));
            int x = 10;
            int y = 100;
            for (int i = 0; i < pubs.size(); i++) {

                //Ajout de l'image de produit
                Publicite p = new PubliciteDAO().findPubById(pubs.get(i).getId());
                String imagePath = "src\\com\\images\\" + p.getId() + ".png";
                ImageIcon icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                        getScaledInstance(80, 70, Image.SCALE_DEFAULT));
                lImage.add(new JLabel(icon1));
                add(lImage.get(i));
                lImage.get(i).setBounds(x + 50, y, 80, 70);
                //Ajout du nom du produit
//                lNom.add(new JLabel(p.getNom()));
//                add(lNom.get(i));
//                lNom.get(i).setBounds(x + 200, y + 20, 90, 30);
                //Ajout du type
                lType.add(new JLabel(p.getType()));
                add(lType.get(i));
                lType.get(i).setBounds(x + 310, y + 20, 110, 30);
                //Ajout du sujet
                lSujet.add(new JLabel(p.getSujet()));
                add(lSujet.get(i));
                lSujet.get(i).setBounds(x + 430, y + 20, 100, 30);
                //Ajout du lieu        
                lLieu.add(new JLabel(p.getLieu()));
                add(lLieu.get(i));
                lLieu.get(i).setBounds(x + 540, y + 20, 30, 30);
                //Ajout da la date       
                lDate.add(new JLabel("" + p.getDate()));
                add(lDate.get(i));
                lDate.get(i).setBounds(x + 640, y + 20, 100, 30);
                //Ajout du bouuton plus de détails
                imagePath = "images\\add.png";
                icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                        getScaledInstance(20, 20, Image.SCALE_DEFAULT));
                lDetails.add(new JLabel(icon1));
                add(lDetails.get(i));
                lDetails.get(i).setBounds(x + 750, y + 20, 30, 30);
                //Ajout du bouuton modifier
                imagePath = "images\\modif.png";
                icon1 = new ImageIcon(new ImageIcon(imagePath).getImage().
                        getScaledInstance(20, 20, Image.SCALE_DEFAULT));
                lModif.add(new JLabel(icon1));
                add(lModif.get(i));
                lModif.get(i).setBounds(x + 790, y + 20, 20, 30);
                //ajout du bouton pour la supprission
                lDelete.add(new JLabel(new ImageIcon("images\\closeEntred.png")));
                add(lDelete.get(i));
                lDelete.get(i).setBounds(x+810, y + 25, 30, 20);
                //Ajout du separateur
                separateur.add(new JSeparator());
                add(separateur.get(i));
                separateur.get(i).setBounds(0, y + 82, 1162, 10);
                y += 100;
            }

        }
        Actions();
    }

    private void Actions() {
        for (int i = 0; i < pubs.size(); i++) {
            int j = i;
            lDelete.get(j).addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    deleteMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    deleteMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    deleteMouseExited(evt, j);
                }

            });
            lDetails.get(i).addMouseListener(new java.awt.event.MouseAdapter() {
//                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    detailMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    detailMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    detailMouseExited(evt, j);
                }

            });
            lModif.get(i).addMouseListener(new java.awt.event.MouseAdapter() {
//                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    ModifMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    ModifMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    ModifMouseExited(evt, j);
                }

            });

        }
    }

    private void deleteMouseClicked(MouseEvent evt, int i) {
 new PubliciteDAO().deletePublicite(pubs.get(i).getId());
        pubs.remove(i);
        removeAll();
        repaint();
        revalidate();
        initComponents();
        loadPubs();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }

    private void deleteMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void deleteMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void detailMouseClicked(MouseEvent evt, int i) {
        new DialogueDetailPublicite(null, true, pubs.get(i).getId())
                .setVisible(true);

//    (modification)           new PubliciteUpdate(pubs.get(i).getId()).setVisible(true);
//     ajout        new PublicteAdd().setVisible(true);

    }

    private void detailMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void detailMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void ModifMouseClicked(MouseEvent evt, int i) {

        new PubliciteUpdate(pubs.get(i).getId()).setVisible(true);
                        repaint();
        revalidate();
        initComponents();
        loadPubs();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
//     ajout        new PublicteAdd().setVisible(true);

    }

    private void ModifMouseEntered(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void ModifMouseExited(MouseEvent evt, int j) {
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

}
