/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Forum;

import DAO.SujetDAO;
import Entity.Sujet;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author gafsi
 */
public class PanelForum extends javax.swing.JPanel {

    /**
     * Creates new form PanelForum
     */
    List<Sujet> listSujets = new ArrayList<>();
    Integer[] lid;
    JLabel[] lTitre;
    private static int userId;

    public PanelForum(int userid) {
        PanelForum.userId = userid;
        initComponents();
        loadSujets();
        sujetActions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitre = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        labelAuteur = new javax.swing.JLabel();
        btnAddSubject = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(null);

        labelTitre.setFont(new java.awt.Font("Adobe Caslon Pro", 3, 20)); // NOI18N
        labelTitre.setForeground(new java.awt.Color(51, 51, 51));
        labelTitre.setText("Titre");
        add(labelTitre);
        labelTitre.setBounds(210, 30, 60, 30);

        Description.setFont(new java.awt.Font("Adobe Caslon Pro", 3, 20)); // NOI18N
        Description.setForeground(new java.awt.Color(51, 51, 51));
        Description.setText("Description");
        add(Description);
        Description.setBounds(410, 30, 100, 30);

        labelAuteur.setFont(new java.awt.Font("Adobe Caslon Pro", 3, 20)); // NOI18N
        labelAuteur.setForeground(new java.awt.Color(51, 51, 51));
        labelAuteur.setText("Auteur");
        add(labelAuteur);
        labelAuteur.setBounds(660, 30, 60, 30);

        btnAddSubject.setText("Ajouter un nouveau sujet");
        btnAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSubjectActionPerformed(evt);
            }
        });
        add(btnAddSubject);
        btnAddSubject.setBounds(150, 453, 180, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSubjectActionPerformed
        // TODO add your handling code here:
        PanelAjouterSujet p=new PanelAjouterSujet(userId);
        removeAll();
        repaint();
        revalidate();
        p.setBounds(0, 0, 1310, 500);
        add(p);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        

    }//GEN-LAST:event_btnAddSubjectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JButton btnAddSubject;
    private javax.swing.JLabel labelAuteur;
    private javax.swing.JLabel labelTitre;
    // End of variables declaration//GEN-END:variables
private void loadSujets() {
        listSujets = new SujetDAO().AfficherSujet();
        lTitre = new JLabel[listSujets.size()];
        JLabel[] lDescription = new JLabel[listSujets.size()];
        JLabel[] lUser = new JLabel[listSujets.size()];
        lid = new Integer[listSujets.size()];
        int x = 210;
        int y = 100;
        for (int i = 0; i < listSujets.size(); i++) {
            // ajout du titre
            lTitre[i] = new JLabel(listSujets.get(i).getTitre());
            lTitre[i].setBounds(x, y, 130, 25);
            lTitre[i].setForeground(Color.black);
            lTitre[i].setFont(new java.awt.Font("Tahoma", 1, 20));
            add(lTitre[i]);
            //ajout de la description
            lDescription[i] = new JLabel(listSujets.get(i).getSujet());
            lDescription[i].setBounds(x + 200, y, 190, 25);
            lDescription[i].setForeground(Color.black);
            lDescription[i].setFont(new java.awt.Font("Tahoma", 2, 14));
            add(lDescription[i]);
            //ajout de l'auteur
            lUser[i] = new JLabel(listSujets.get(i).getUser().getUsername());
            lUser[i].setBounds(x + 450, y, 90, 25);
            lUser[i].setForeground(Color.black);
            lUser[i].setFont(new java.awt.Font("Tahoma", 2, 14));
            y += 60;
            add(lUser[i]);
            //ajout de l'id du sujet
            lid[i] = listSujets.get(i).getId();
        }

    }

    private void sujetActions() {
        for (int i = 0; i < lTitre.length; i++) {
            int j = i;
            lTitre[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    titreMouseClicked(evt, j);
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    titreMouseEntered(evt, j);
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    titreMouseExited(evt, j);
                }

            });

        }
    }

    private void titreMouseClicked(MouseEvent evt, int i) {
        removeAll();
        repaint();
        revalidate();
        PanelSujetDisplay p = new PanelSujetDisplay(lid[i], userId);
        p.setBounds(0, 0, 1310, 500);
        add(p);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }

    private void titreMouseEntered(MouseEvent evt, int j) {
        lTitre[j].setForeground(Color.BLUE);
        setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void titreMouseExited(MouseEvent evt, int j) {
        lTitre[j].setForeground(Color.black);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
}
